#这里没有指定profiles的部分为公共部分
spring:
  application:
    name: discovery
---
spring:
  #指定当前配置profiles=server1
  profiles: server1
server:
  #当profiles=server1时，应用的端口为8761
  port: 8761
eureka:
  client:
    service-url:
      #当前应用向端口为8762的服务进行注册
      defaultZone: http://localhost:8762/eureka
---
spring:
  #指定当前配置profiles=server2
  profiles: server2
server:
  #当profiles=server1时，应用的端口为8762
  port: 8762
eureka:
  client:
    service-url:
      #当前应用向端口为8761的服务进行注册
      defaultZone: http://localhost:8761/eureka