spring:
  datasource:
    url: jdbc:mysql://106.75.143.161:3306/qpydemos
    username: root
    password: mysql.123
  jpa:
    database: mysql
logging:
  level: debug
---
#当启用server{x}时，连接的是单体注册中心。用于本地开发测试，最多可启动3台
spring:
  profiles: server0
  application:
    name: ms-movie
server:
  port: 8770
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8760/eureka
---
spring:
  profiles: server1
  application:
    name: ms-movie
server:
  port: 8771
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8760/eureka
---
spring:
  profiles: server2
  application:
    name: ms-movie
server:
  port: 8772
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8760/eureka
---
#当启用servers{x}时，连接的是高可用注册中心。用于本地开发测试，最多可启动3台
spring:
  profiles: servers1
  application:
    name: ms-movie
server:
  port: 8773
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
---
spring:
  profiles: servers2
  application:
    name: ms-movie
server:
  port: 8774
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
---
spring:
  profiles: servers3
  application:
    name: ms-movie
server:
  port: 8775
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka

