#Spring Boot+MySQL+JPA
#ref:https://spring.io/guides/gs/accessing-data-mysql/
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
  datasource:
    url: jdbc:mysql://106.75.143.161:3306/qpydemos
    #这里使用的是username/password，而非data-user/data-password
    username: root
    password: mysql.123
  session:
    store-type: hash_map
  freemarker:
    #要支持freemarker，必须设置RequestContext属性的简称
    request-context-attribute: request
app:
  department:
    total: 2
    name: 'G端事业部'

single:
  property:
    value: 属性也可以直接获取

environments:
  dev:
    name: Developer Setup
    url: http://dev.bar.com
  prod:
    name: My Cool App
    url: http://foo.bar.com


logging:
  path: d://
  level: debug

