server:
  port: 8771
eureka:
  client:
    service-url:
      #这里建议要配置相应的eureka server对应的服务地址
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
spring:
  application:
    name: ms-user
