
#这里没有指定profiles的部分为公共部分
#这里的安全认证信息需要添加spring-boot-starter-security依赖才生效
spring:
  application:
    name: discovery-eureka
security:
  user:
    name: admin
    password: admin
  basic:
    enabled: true

#这里用---进行分段配置，每一段需指定一个profiles
---
#一台server
spring:
  profiles: server
server:
  port: 8760
eureka:
  client:
    service-url:
      #当前应用与eureka服务的交互(查询或注册服务)地址
      defaultZone: http://localhost:8760/discovery-eureka
    #是否将自己注册到eureka服务上，这里本身就是server，所以为false
    register-with-eureka: false
  server:
    enable-self-preservation: false
---
#以下为两台（servers1&servers2）互相注册的高可用部署
spring:
  #指定当前配置profiles=servers1
  profiles: servers1
server:
  #当profiles=server1时，应用的端口为8761
  port: 8761
eureka:
  client:
    service-url:
      #当前应用向端口为8762的服务进行注册
      defaultZone: http://localhost:8762/discovery-eureka
---
spring:
  #指定当前配置profiles=servers2
  profiles: servers2
server:
  #当profiles=server1时，应用的端口为8762
  port: 8762
eureka:
  client:
    service-url:
      #当前应用向端口为8761的服务进行注册
      defaultZone: http://localhost:8761/discovery-eureka